
// Code generated by stanc v2.30.0-63-g1ae9de8f
#include <stan/model/model_header.hpp>
namespace m_pp_model_namespace {

using stan::model::model_base_crtp;
using namespace stan::math;


stan::math::profile_map profiles__;
static constexpr std::array<const char*, 23> locations_array__ = 
{" (found before start of program)",
 " (in '/Users/rob/.julia/dev/ROSStanPluto/notebooks/Playgrounds/ARM/Radon/tmp/m_pp.stan', line 9, column 2 to column 16)",
 " (in '/Users/rob/.julia/dev/ROSStanPluto/notebooks/Playgrounds/ARM/Radon/tmp/m_pp.stan', line 10, column 2 to column 28)",
 " (in '/Users/rob/.julia/dev/ROSStanPluto/notebooks/Playgrounds/ARM/Radon/tmp/m_pp.stan', line 11, column 2 to column 59)",
 " (in '/Users/rob/.julia/dev/ROSStanPluto/notebooks/Playgrounds/ARM/Radon/tmp/m_pp.stan', line 12, column 2 to column 12)",
 " (in '/Users/rob/.julia/dev/ROSStanPluto/notebooks/Playgrounds/ARM/Radon/tmp/m_pp.stan', line 13, column 2 to column 22)",
 " (in '/Users/rob/.julia/dev/ROSStanPluto/notebooks/Playgrounds/ARM/Radon/tmp/m_pp.stan', line 24, column 2 to column 68)",
 " (in '/Users/rob/.julia/dev/ROSStanPluto/notebooks/Playgrounds/ARM/Radon/tmp/m_pp.stan', line 16, column 2 to column 46)",
 " (in '/Users/rob/.julia/dev/ROSStanPluto/notebooks/Playgrounds/ARM/Radon/tmp/m_pp.stan', line 17, column 2 to column 40)",
 " (in '/Users/rob/.julia/dev/ROSStanPluto/notebooks/Playgrounds/ARM/Radon/tmp/m_pp.stan', line 18, column 2 to column 23)",
 " (in '/Users/rob/.julia/dev/ROSStanPluto/notebooks/Playgrounds/ARM/Radon/tmp/m_pp.stan', line 19, column 2 to column 24)",
 " (in '/Users/rob/.julia/dev/ROSStanPluto/notebooks/Playgrounds/ARM/Radon/tmp/m_pp.stan', line 20, column 2 to column 27)",
 " (in '/Users/rob/.julia/dev/ROSStanPluto/notebooks/Playgrounds/ARM/Radon/tmp/m_pp.stan', line 21, column 2 to column 30)",
 " (in '/Users/rob/.julia/dev/ROSStanPluto/notebooks/Playgrounds/ARM/Radon/tmp/m_pp.stan', line 2, column 2 to column 17)",
 " (in '/Users/rob/.julia/dev/ROSStanPluto/notebooks/Playgrounds/ARM/Radon/tmp/m_pp.stan', line 3, column 2 to column 17)",
 " (in '/Users/rob/.julia/dev/ROSStanPluto/notebooks/Playgrounds/ARM/Radon/tmp/m_pp.stan', line 4, column 8 to column 9)",
 " (in '/Users/rob/.julia/dev/ROSStanPluto/notebooks/Playgrounds/ARM/Radon/tmp/m_pp.stan', line 4, column 2 to column 40)",
 " (in '/Users/rob/.julia/dev/ROSStanPluto/notebooks/Playgrounds/ARM/Radon/tmp/m_pp.stan', line 5, column 9 to column 10)",
 " (in '/Users/rob/.julia/dev/ROSStanPluto/notebooks/Playgrounds/ARM/Radon/tmp/m_pp.stan', line 5, column 2 to column 14)",
 " (in '/Users/rob/.julia/dev/ROSStanPluto/notebooks/Playgrounds/ARM/Radon/tmp/m_pp.stan', line 6, column 9 to column 10)",
 " (in '/Users/rob/.julia/dev/ROSStanPluto/notebooks/Playgrounds/ARM/Radon/tmp/m_pp.stan', line 6, column 2 to column 14)",
 " (in '/Users/rob/.julia/dev/ROSStanPluto/notebooks/Playgrounds/ARM/Radon/tmp/m_pp.stan', line 11, column 50 to column 51)",
 " (in '/Users/rob/.julia/dev/ROSStanPluto/notebooks/Playgrounds/ARM/Radon/tmp/m_pp.stan', line 24, column 8 to column 9)"};




class m_pp_model final : public model_base_crtp<m_pp_model> {

 private:
  int N;
  int J;
  std::vector<int> county;
  Eigen::Matrix<double, -1, 1> x_data__;
  Eigen::Matrix<double, -1, 1> y_data__; 
  Eigen::Map<Eigen::Matrix<double, -1, 1>> x{nullptr, 0};
  Eigen::Map<Eigen::Matrix<double, -1, 1>> y{nullptr, 0};
 
 public:
  ~m_pp_model() { }
  
  inline std::string model_name() const final { return "m_pp_model"; }

  inline std::vector<std::string> model_compile_info() const noexcept {
    return std::vector<std::string>{"stanc_version = stanc3 v2.30.0-63-g1ae9de8f", "stancflags = --warn-pedantic --O1"};
  }
  
  
  m_pp_model(stan::io::var_context& context__,
             unsigned int random_seed__ = 0,
             std::ostream* pstream__ = nullptr) : model_base_crtp(0) {
    int current_statement__ = 0;
    using local_scalar_t__ = double ;
    boost::ecuyer1988 base_rng__ = 
        stan::services::util::create_rng(random_seed__, 0);
    (void) base_rng__;  // suppress unused var warning
    static constexpr const char* function__ = "m_pp_model_namespace::m_pp_model";
    (void) function__;  // suppress unused var warning
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    (void) DUMMY_VAR__;  // suppress unused var warning
    try {
      int pos__;
      pos__ = 1;
      current_statement__ = 13;
      context__.validate_dims("data initialization","N","int",
           std::vector<size_t>{});
      N = std::numeric_limits<int>::min();
      
      
      current_statement__ = 13;
      N = context__.vals_i("N")[(1 - 1)];
      current_statement__ = 13;
      stan::math::check_greater_or_equal(function__, "N", N, 1);
      current_statement__ = 14;
      context__.validate_dims("data initialization","J","int",
           std::vector<size_t>{});
      J = std::numeric_limits<int>::min();
      
      
      current_statement__ = 14;
      J = context__.vals_i("J")[(1 - 1)];
      current_statement__ = 14;
      stan::math::check_greater_or_equal(function__, "J", J, 1);
      current_statement__ = 15;
      stan::math::validate_non_negative_index("county", "N", N);
      current_statement__ = 16;
      context__.validate_dims("data initialization","county","int",
           std::vector<size_t>{static_cast<size_t>(N)});
      county = std::vector<int>(N, std::numeric_limits<int>::min());
      
      
      current_statement__ = 16;
      county = context__.vals_i("county");
      current_statement__ = 16;
      stan::math::check_greater_or_equal(function__, "county", county, 1);
      current_statement__ = 16;
      stan::math::check_less_or_equal(function__, "county", county, J);
      current_statement__ = 17;
      stan::math::validate_non_negative_index("x", "N", N);
      current_statement__ = 18;
      context__.validate_dims("data initialization","x","double",
           std::vector<size_t>{static_cast<size_t>(N)});
      x_data__ = 
        Eigen::Matrix<double, -1, 1>::Constant(N,
          std::numeric_limits<double>::quiet_NaN());
      new (&x) Eigen::Map<Eigen::Matrix<double, -1, 1>>(x_data__.data(), N);
      
      {
        std::vector<local_scalar_t__> x_flat__;
        current_statement__ = 18;
        x_flat__ = context__.vals_r("x");
        current_statement__ = 18;
        pos__ = 1;
        current_statement__ = 18;
        for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
          current_statement__ = 18;
          stan::model::assign(x, x_flat__[(pos__ - 1)],
            "assigning variable x", stan::model::index_uni(sym1__));
          current_statement__ = 18;
          pos__ = (pos__ + 1);
        }
      }
      current_statement__ = 19;
      stan::math::validate_non_negative_index("y", "N", N);
      current_statement__ = 20;
      context__.validate_dims("data initialization","y","double",
           std::vector<size_t>{static_cast<size_t>(N)});
      y_data__ = 
        Eigen::Matrix<double, -1, 1>::Constant(N,
          std::numeric_limits<double>::quiet_NaN());
      new (&y) Eigen::Map<Eigen::Matrix<double, -1, 1>>(y_data__.data(), N);
      
      {
        std::vector<local_scalar_t__> y_flat__;
        current_statement__ = 20;
        y_flat__ = context__.vals_r("y");
        current_statement__ = 20;
        pos__ = 1;
        current_statement__ = 20;
        for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
          current_statement__ = 20;
          stan::model::assign(y, y_flat__[(pos__ - 1)],
            "assigning variable y", stan::model::index_uni(sym1__));
          current_statement__ = 20;
          pos__ = (pos__ + 1);
        }
      }
      current_statement__ = 21;
      stan::math::validate_non_negative_index("alpha", "J", J);
      current_statement__ = 22;
      stan::math::validate_non_negative_index("y_rep", "N", N);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    num_params_r__ = 1 + 1 + J + 1 + 1;
    
  }
  
  template <bool propto__, bool jacobian__ , typename VecR, typename VecI, 
  stan::require_vector_like_t<VecR>* = nullptr, 
  stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr> 
  inline stan::scalar_type_t<VecR> log_prob_impl(VecR& params_r__,
                                                 VecI& params_i__,
                                                 std::ostream* pstream__ = nullptr) const {
    using T__ = stan::scalar_type_t<VecR>;
    using local_scalar_t__ = T__;
    T__ lp__(0.0);
    stan::math::accumulator<T__> lp_accum__;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    int current_statement__ = 0;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    (void) DUMMY_VAR__;  // suppress unused var warning
    static constexpr const char* function__ = "m_pp_model_namespace::log_prob";
    (void) function__;  // suppress unused var warning
    
    try {
      local_scalar_t__ mu_alpha;
      current_statement__ = 1;
      mu_alpha = in__.template read<local_scalar_t__>();
      local_scalar_t__ sigma_alpha;
      current_statement__ = 2;
      sigma_alpha = in__.template read_constrain_lb<local_scalar_t__, 
                      jacobian__>(0, lp__);
      stan::conditional_var_value_t<local_scalar_t__, 
        Eigen::Matrix<local_scalar_t__, -1, 1>> alpha;
      current_statement__ = 3;
      alpha = in__.template read_constrain_offset_multiplier<
                stan::conditional_var_value_t<local_scalar_t__, 
                  Eigen::Matrix<local_scalar_t__, -1, 1>>, jacobian__>(
                mu_alpha, sigma_alpha, lp__, J);
      local_scalar_t__ beta;
      current_statement__ = 4;
      beta = in__.template read<local_scalar_t__>();
      local_scalar_t__ sigma;
      current_statement__ = 5;
      sigma = in__.template read_constrain_lb<local_scalar_t__, jacobian__>(
                0, lp__);
      {
        current_statement__ = 7;
        lp_accum__.add(
          stan::math::normal_lpdf<propto__>(y,
            stan::math::fma(beta, x,
              stan::model::rvalue(alpha, "alpha",
                stan::model::index_multi(county))), sigma));
        current_statement__ = 8;
        lp_accum__.add(
          stan::math::normal_lpdf<propto__>(alpha, mu_alpha, sigma_alpha));
        current_statement__ = 9;
        lp_accum__.add(stan::math::normal_lpdf<propto__>(beta, 0, 10));
        current_statement__ = 10;
        lp_accum__.add(stan::math::normal_lpdf<propto__>(sigma, 0, 10));
        current_statement__ = 11;
        lp_accum__.add(stan::math::normal_lpdf<propto__>(mu_alpha, 0, 10));
        current_statement__ = 12;
        lp_accum__.add(stan::math::normal_lpdf<propto__>(sigma_alpha, 0, 10));
      }
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    lp_accum__.add(lp__);
    return lp_accum__.sum();
    } // log_prob_impl() 
    
  template <typename RNG, typename VecR, typename VecI, typename VecVar, 
  stan::require_vector_like_vt<std::is_floating_point, VecR>* = nullptr, 
  stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr, 
  stan::require_vector_vt<std::is_floating_point, VecVar>* = nullptr> 
  inline void write_array_impl(RNG& base_rng__, VecR& params_r__,
                               VecI& params_i__, VecVar& vars__,
                               const bool emit_transformed_parameters__ = true,
                               const bool emit_generated_quantities__ = true,
                               std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    stan::io::serializer<local_scalar_t__> out__(vars__);
    static constexpr bool propto__ = true;
    (void) propto__;
    double lp__ = 0.0;
    (void) lp__;  // dummy to suppress unused var warning
    int current_statement__ = 0; 
    stan::math::accumulator<double> lp_accum__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    constexpr bool jacobian__ = false;
    (void) DUMMY_VAR__;  // suppress unused var warning
    static constexpr const char* function__ = "m_pp_model_namespace::write_array";
    (void) function__;  // suppress unused var warning
    
    try {
      double mu_alpha;
      current_statement__ = 1;
      mu_alpha = in__.template read<local_scalar_t__>();
      double sigma_alpha;
      current_statement__ = 2;
      sigma_alpha = in__.template read_constrain_lb<local_scalar_t__, 
                      jacobian__>(0, lp__);
      Eigen::Matrix<double, -1, 1> alpha;
      current_statement__ = 3;
      alpha = in__.template read_constrain_offset_multiplier<
                Eigen::Matrix<local_scalar_t__, -1, 1>, jacobian__>(mu_alpha,
                sigma_alpha, lp__, J);
      double beta;
      current_statement__ = 4;
      beta = in__.template read<local_scalar_t__>();
      double sigma;
      current_statement__ = 5;
      sigma = in__.template read_constrain_lb<local_scalar_t__, jacobian__>(
                0, lp__);
      out__.write(mu_alpha);
      out__.write(sigma_alpha);
      out__.write(alpha);
      out__.write(beta);
      out__.write(sigma);
      if (stan::math::logical_negation((stan::math::primitive_value(
            emit_transformed_parameters__) || stan::math::primitive_value(
            emit_generated_quantities__)))) {
        return ;
      } 
      if (stan::math::logical_negation(emit_generated_quantities__)) {
        return ;
      } 
      std::vector<double> y_rep =
         std::vector<double>(N, std::numeric_limits<double>::quiet_NaN());
      current_statement__ = 6;
      stan::model::assign(y_rep,
        stan::math::normal_rng(
          stan::math::fma(beta, x,
            stan::model::rvalue(alpha, "alpha",
              stan::model::index_multi(county))), sigma, base_rng__),
        "assigning variable y_rep");
      out__.write(y_rep);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    } // write_array_impl() 
    
  template <typename VecVar, typename VecI, 
  stan::require_vector_t<VecVar>* = nullptr, 
  stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr> 
  inline void transform_inits_impl(VecVar& params_r__, VecI& params_i__,
                                   VecVar& vars__,
                                   std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    stan::io::serializer<local_scalar_t__> out__(vars__);
    int current_statement__ = 0;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    
    try {
      int pos__;
      pos__ = 1;
      local_scalar_t__ mu_alpha;
      mu_alpha = in__.read<local_scalar_t__>();
      out__.write(mu_alpha);
      local_scalar_t__ sigma_alpha;
      sigma_alpha = in__.read<local_scalar_t__>();
      out__.write_free_lb(0, sigma_alpha);
      Eigen::Matrix<local_scalar_t__, -1, 1> alpha =
         Eigen::Matrix<local_scalar_t__, -1, 1>::Constant(J, DUMMY_VAR__);
      for (int sym1__ = 1; sym1__ <= J; ++sym1__) {
        stan::model::assign(alpha, in__.read<local_scalar_t__>(),
          "assigning variable alpha", stan::model::index_uni(sym1__));
      }
      out__.write_free_offset_multiplier(mu_alpha, sigma_alpha, alpha);
      local_scalar_t__ beta;
      beta = in__.read<local_scalar_t__>();
      out__.write(beta);
      local_scalar_t__ sigma;
      sigma = in__.read<local_scalar_t__>();
      out__.write_free_lb(0, sigma);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    } // transform_inits_impl() 
    
  inline void get_param_names(std::vector<std::string>& names__) const {
    
    names__ = std::vector<std::string>{"mu_alpha", "sigma_alpha", "alpha",
      "beta", "sigma", "y_rep"};
    
    } // get_param_names() 
    
  inline void get_dims(std::vector<std::vector<size_t>>& dimss__) const {
    
    dimss__ = std::vector<std::vector<size_t>>{std::vector<size_t>{},
      std::vector<size_t>{}, std::vector<size_t>{static_cast<size_t>(J)},
      std::vector<size_t>{}, std::vector<size_t>{},
      std::vector<size_t>{static_cast<size_t>(N)}};
    
    } // get_dims() 
    
  inline void constrained_param_names(
                                      std::vector<std::string>& param_names__,
                                      bool emit_transformed_parameters__ = true,
                                      bool emit_generated_quantities__ = true) const
    final {
    
    param_names__.emplace_back(std::string() + "mu_alpha");
    param_names__.emplace_back(std::string() + "sigma_alpha");
    for (int sym1__ = 1; sym1__ <= J; ++sym1__) {
      {
        param_names__.emplace_back(std::string() + "alpha" + '.' + std::to_string(sym1__));
      } 
    }
    param_names__.emplace_back(std::string() + "beta");
    param_names__.emplace_back(std::string() + "sigma");
    if (emit_transformed_parameters__) {
      
    }
    
    if (emit_generated_quantities__) {
      for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
        {
          param_names__.emplace_back(std::string() + "y_rep" + '.' + std::to_string(sym1__));
        } 
      }
    }
    
    } // constrained_param_names() 
    
  inline void unconstrained_param_names(
                                        std::vector<std::string>& param_names__,
                                        bool emit_transformed_parameters__ = true,
                                        bool emit_generated_quantities__ = true) const
    final {
    
    param_names__.emplace_back(std::string() + "mu_alpha");
    param_names__.emplace_back(std::string() + "sigma_alpha");
    for (int sym1__ = 1; sym1__ <= J; ++sym1__) {
      {
        param_names__.emplace_back(std::string() + "alpha" + '.' + std::to_string(sym1__));
      } 
    }
    param_names__.emplace_back(std::string() + "beta");
    param_names__.emplace_back(std::string() + "sigma");
    if (emit_transformed_parameters__) {
      
    }
    
    if (emit_generated_quantities__) {
      for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
        {
          param_names__.emplace_back(std::string() + "y_rep" + '.' + std::to_string(sym1__));
        } 
      }
    }
    
    } // unconstrained_param_names() 
    
  inline std::string get_constrained_sizedtypes() const {
    
    return std::string("[{\"name\":\"mu_alpha\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"sigma_alpha\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"alpha\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(J) + "},\"block\":\"parameters\"},{\"name\":\"beta\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"sigma\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"y_rep\",\"type\":{\"name\":\"array\",\"length\":" + std::to_string(N) + ",\"element_type\":{\"name\":\"real\"}},\"block\":\"generated_quantities\"}]");
    
    } // get_constrained_sizedtypes() 
    
  inline std::string get_unconstrained_sizedtypes() const {
    
    return std::string("[{\"name\":\"mu_alpha\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"sigma_alpha\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"alpha\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(J) + "},\"block\":\"parameters\"},{\"name\":\"beta\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"sigma\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"y_rep\",\"type\":{\"name\":\"array\",\"length\":" + std::to_string(N) + ",\"element_type\":{\"name\":\"real\"}},\"block\":\"generated_quantities\"}]");
    
    } // get_unconstrained_sizedtypes() 
    
  
    // Begin method overload boilerplate
    template <typename RNG>
    inline void write_array(RNG& base_rng,
                            Eigen::Matrix<double,Eigen::Dynamic,1>& params_r,
                            Eigen::Matrix<double,Eigen::Dynamic,1>& vars,
                            const bool emit_transformed_parameters = true,
                            const bool emit_generated_quantities = true,
                            std::ostream* pstream = nullptr) const {
      const size_t num_params__ = 
  ((((1 + 1) + J) + 1) + 1);
      const size_t num_transformed = emit_transformed_parameters * 0;
      const size_t num_gen_quantities = emit_generated_quantities * N;
      const size_t num_to_write = num_params__ + num_transformed +
        num_gen_quantities;
      std::vector<int> params_i;
      vars = Eigen::Matrix<double, Eigen::Dynamic, 1>::Constant(num_to_write,
        std::numeric_limits<double>::quiet_NaN());
      write_array_impl(base_rng, params_r, params_i, vars,
        emit_transformed_parameters, emit_generated_quantities, pstream);
    }

    template <typename RNG>
    inline void write_array(RNG& base_rng, std::vector<double>& params_r,
                            std::vector<int>& params_i,
                            std::vector<double>& vars,
                            bool emit_transformed_parameters = true,
                            bool emit_generated_quantities = true,
                            std::ostream* pstream = nullptr) const {
      const size_t num_params__ = 
  ((((1 + 1) + J) + 1) + 1);
      const size_t num_transformed = emit_transformed_parameters * 0;
      const size_t num_gen_quantities = emit_generated_quantities * N;
      const size_t num_to_write = num_params__ + num_transformed +
        num_gen_quantities;
      vars = std::vector<double>(num_to_write,
        std::numeric_limits<double>::quiet_NaN());
      write_array_impl(base_rng, params_r, params_i, vars,
        emit_transformed_parameters, emit_generated_quantities, pstream);
    }

    template <bool propto__, bool jacobian__, typename T_>
    inline T_ log_prob(Eigen::Matrix<T_,Eigen::Dynamic,1>& params_r,
                       std::ostream* pstream = nullptr) const {
      Eigen::Matrix<int, -1, 1> params_i;
      return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
    }

    template <bool propto__, bool jacobian__, typename T__>
    inline T__ log_prob(std::vector<T__>& params_r,
                        std::vector<int>& params_i,
                        std::ostream* pstream = nullptr) const {
      return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
    }


    inline void transform_inits(const stan::io::var_context& context,
                         Eigen::Matrix<double, Eigen::Dynamic, 1>& params_r,
                         std::ostream* pstream = nullptr) const final {
      std::vector<double> params_r_vec(params_r.size());
      std::vector<int> params_i;
      transform_inits(context, params_i, params_r_vec, pstream);
      params_r = Eigen::Map<Eigen::Matrix<double,Eigen::Dynamic,1>>(
        params_r_vec.data(), params_r_vec.size());
    }

  inline void transform_inits(const stan::io::var_context& context,
                              std::vector<int>& params_i,
                              std::vector<double>& vars,
                              std::ostream* pstream__ = nullptr) const {
     constexpr std::array<const char*, 5> names__{"mu_alpha", "sigma_alpha",
      "alpha", "beta", "sigma"};
      const std::array<Eigen::Index, 5> constrain_param_sizes__{1, 1, 
       J, 1, 1};
      const auto num_constrained_params__ = std::accumulate(
        constrain_param_sizes__.begin(), constrain_param_sizes__.end(), 0);
    
     std::vector<double> params_r_flat__(num_constrained_params__);
     Eigen::Index size_iter__ = 0;
     Eigen::Index flat_iter__ = 0;
     for (auto&& param_name__ : names__) {
       const auto param_vec__ = context.vals_r(param_name__);
       for (Eigen::Index i = 0; i < constrain_param_sizes__[size_iter__]; ++i) {
         params_r_flat__[flat_iter__] = param_vec__[i];
         ++flat_iter__;
       }
       ++size_iter__;
     }
     vars.resize(num_params_r__);
     transform_inits_impl(params_r_flat__, params_i, vars, pstream__);
    } // transform_inits() 
    
};
}
using stan_model = m_pp_model_namespace::m_pp_model;

#ifndef USING_R

// Boilerplate
stan::model::model_base& new_model(
        stan::io::var_context& data_context,
        unsigned int seed,
        std::ostream* msg_stream) {
  stan_model* m = new stan_model(data_context, seed, msg_stream);
  return *m;
}

stan::math::profile_map& get_stan_profile_data() {
  return m_pp_model_namespace::profiles__;
}

#endif


